arquivos do servidor node js + socket io
https://github.com/marcola123/RpgUnity-server/blob/4a7ccc5846dbe64fb6d2075ed05b739d3483eb7a/Server%20-%20Copia/server.js
https://github.com/marcola123/RpgUnity-server/blob/4a7ccc5846dbe64fb6d2075ed05b739d3483eb7a/Server%20-%20Copia/package.json
https://github.com/marcola123/RpgUnity-server/blob/4a7ccc5846dbe64fb6d2075ed05b739d3483eb7a/Server%20-%20Copia/src/config/config.js
https://github.com/marcola123/RpgUnity-server/blob/4a7ccc5846dbe64fb6d2075ed05b739d3483eb7a/Server%20-%20Copia/src/config/database.js
https://github.com/marcola123/RpgUnity-server/blob/4a7ccc5846dbe64fb6d2075ed05b739d3483eb7a/Server%20-%20Copia/src/controllers/authController.js
https://github.com/marcola123/RpgUnity-server/blob/4a7ccc5846dbe64fb6d2075ed05b739d3483eb7a/Server%20-%20Copia/src/controllers/characterController.js
https://github.com/marcola123/RpgUnity-server/blob/4a7ccc5846dbe64fb6d2075ed05b739d3483eb7a/Server%20-%20Copia/src/controllers/combatController.js
https://github.com/marcola123/RpgUnity-server/blob/4a7ccc5846dbe64fb6d2075ed05b739d3483eb7a/Server%20-%20Copia/src/controllers/inventoryController.js
https://github.com/marcola123/RpgUnity-server/blob/4a7ccc5846dbe64fb6d2075ed05b739d3483eb7a/Server%20-%20Copia/src/controllers/playerController.js
https://github.com/marcola123/RpgUnity-server/blob/4a7ccc5846dbe64fb6d2075ed05b739d3483eb7a/Server%20-%20Copia/src/controllers/serverController.js
https://github.com/marcola123/RpgUnity-server/blob/4a7ccc5846dbe64fb6d2075ed05b739d3483eb7a/Server%20-%20Copia/src/models/Account.js
https://github.com/marcola123/RpgUnity-server/blob/4a7ccc5846dbe64fb6d2075ed05b739d3483eb7a/Server%20-%20Copia/src/models/Character.js
https://github.com/marcola123/RpgUnity-server/blob/4a7ccc5846dbe64fb6d2075ed05b739d3483eb7a/Server%20-%20Copia/src/models/Item.js
https://github.com/marcola123/RpgUnity-server/blob/4a7ccc5846dbe64fb6d2075ed05b739d3483eb7a/Server%20-%20Copia/src/models/Monster.js
https://github.com/marcola123/RpgUnity-server/blob/4a7ccc5846dbe64fb6d2075ed05b739d3483eb7a/Server%20-%20Copia/src/models/Server.js
https://github.com/marcola123/RpgUnity-server/blob/4a7ccc5846dbe64fb6d2075ed05b739d3483eb7a/Server%20-%20Copia/src/routes/serverRoutes.js
https://github.com/marcola123/RpgUnity-server/blob/4a7ccc5846dbe64fb6d2075ed05b739d3483eb7a/Server%20-%20Copia/src/sockets/authEvents.js
https://github.com/marcola123/RpgUnity-server/blob/4a7ccc5846dbe64fb6d2075ed05b739d3483eb7a/Server%20-%20Copia/src/sockets/characterEvents.js
https://github.com/marcola123/RpgUnity-server/blob/4a7ccc5846dbe64fb6d2075ed05b739d3483eb7a/Server%20-%20Copia/src/sockets/combatEvents.js
https://github.com/marcola123/RpgUnity-server/blob/4a7ccc5846dbe64fb6d2075ed05b739d3483eb7a/Server%20-%20Copia/src/sockets/inventoryEvents.js
https://github.com/marcola123/RpgUnity-server/blob/4a7ccc5846dbe64fb6d2075ed05b739d3483eb7a/Server%20-%20Copia/src/sockets/playerEvents.js
https://github.com/marcola123/RpgUnity-server/blob/4a7ccc5846dbe64fb6d2075ed05b739d3483eb7a/Server%20-%20Copia/src/utils/helpers.js
https://github.com/marcola123/RpgUnity-server/blob/4a7ccc5846dbe64fb6d2075ed05b739d3483eb7a/Server%20-%20Copia/src/utils/logger.js
https://github.com/marcola123/RpgUnity-server/blob/4a7ccc5846dbe64fb6d2075ed05b739d3483eb7a/Server%20-%20Copia/src/utils/serverManager.js

arquivos da unity 6 para conectar com o servidor usando https://github.com/itisnajim/SocketIOUnity

https://github.com/marcola123/RpgUnity-server/blob/4a7ccc5846dbe64fb6d2075ed05b739d3483eb7a/assets/Scripts/AuthManager.cs
https://github.com/marcola123/RpgUnity-server/blob/4a7ccc5846dbe64fb6d2075ed05b739d3483eb7a/assets/Scripts/CharacterButton.cs
https://github.com/marcola123/RpgUnity-server/blob/4a7ccc5846dbe64fb6d2075ed05b739d3483eb7a/assets/Scripts/CharacterManager.cs
https://github.com/marcola123/RpgUnity-server/blob/4a7ccc5846dbe64fb6d2075ed05b739d3483eb7a/assets/Scripts/CharacterSocketHandler.cs
https://github.com/marcola123/RpgUnity-server/blob/4a7ccc5846dbe64fb6d2075ed05b739d3483eb7a/assets/Scripts/GameManager.cs
https://github.com/marcola123/RpgUnity-server/blob/4a7ccc5846dbe64fb6d2075ed05b739d3483eb7a/assets/Scripts/MainThreadDispatcher.cs
https://github.com/marcola123/RpgUnity-server/blob/4a7ccc5846dbe64fb6d2075ed05b739d3483eb7a/assets/Scripts/PlayerController.CS
https://github.com/marcola123/RpgUnity-server/blob/4a7ccc5846dbe64fb6d2075ed05b739d3483eb7a/assets/Scripts/ServerButton.cs
https://github.com/marcola123/RpgUnity-server/blob/4a7ccc5846dbe64fb6d2075ed05b739d3483eb7a/assets/Scripts/ServerInfo.cs
https://github.com/marcola123/RpgUnity-server/blob/4a7ccc5846dbe64fb6d2075ed05b739d3483eb7a/assets/Scripts/SocketIOManager.cs